### ISSUE TITLE
elective.get_SupplyCancel()中抛出SystemException

### ISSUE THREAD

**Issue by jy5275** [zhongxinghong/PKUAutoElective#1]
在elective.get_SupplyCancel()中总是抛出SystemException异常

配置信息：
csv_coding = gbk
refresh_interval = 8
random_deviation = 0.2
iaaa_relogin_interval = 7200
iaaa_client_timeout = 30
elective_client_timeout = 60
debug_print_request = false
debug_dump_request = false

终端输出：
...
[INFO] loop, 13:51:10, Get SupplyCancel page
[ERROR] loop.error, 13:51:36, [310] 您尚未登录或者会话超时,请重新登录。
[WARNING] loop, 13:52:44, SystemException encountered
[INFO] loop, 13:53:58, 
[INFO] loop, 13:53:58, ======== END Loop 3 ========
...

**Comment by kalonigod** [comment]
me too,

**Comment by zhongxinghong** [comment]
@jy5275 请问是双学位账号吗？如果是双学位账号，需要修改 `dual_degree` 为 `true`，否则会少一步登录。如果不是双学位的话... 可能需要加一下微信 orz ...

**Comment by kalonigod** [comment]
> @jy5275 请问是双学位账号吗？如果是双学位账号，需要修改 `dual_degree` 为 `true`，否则会少一步登录。如果不是双学位的话... 可能需要加一下微信 orz ...

我不是双学位账号，不过不知道为什么也会出现一模一样的问题，配置都正确的，早上还可以，这阵就一直出现这个错误

**Comment by jy5275** [comment]
@zhongxinghong 感谢，已经解决。我有双学位且在主学位中选课，但一开始将dual_degree设置为false了，改成true就对了。谢谢！

**Comment by kalonigod** [comment]
> @zhongxinghong 感谢，已经解决。我有双学位且在主学位中选课，但一开始将dual_degree设置为false了，改成true就对了。谢谢！

sogo, 我也是酱紫

**Comment by jy5275** [comment]
@kalonigod 或许检查一下student_ID, password, dual_degree, identity这四个字段吧，具体的我也布吉岛了_(:з)∠)_
