### ISSUE TITLE
无法选取有空位的课

### ISSUE THREAD

**Issue by Poiw** [zhongxinghong/PKUAutoElective#17]
### Check List

- [ ] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [ ] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [Ubuntu 18 ]
Python version: [python3.6] 
AutoElective version: [ 3.0.3] \( run `python3 main.py --version` )

### Config

supply_cancel_page = 1
refresh_interval = 2
random_deviation = 0.2
iaaa_client_timeout = 30
elective_client_timeout = 60
elective_client_pool_size = 3
login_loop_interval = 2
debug_print_request = false
debug_dump_request = false

[monitor]

; host   str
; port   int

host = 127.0.0.1
port = 7074

#### What

无法选取有空位的课

#### Console Log

[INFO] loop, 10:59:11, Try to elect Course(JavaScript语言Web程序设计, 1, 信息科学技术学院, 90 / 58)
[INFO] loop, 10:59:11, Fetch a captcha
[ERROR] loop.error, 10:59:11, argmax() got an unexpected keyword argument 'axis'
Traceback (most recent call last):
  File "/home/poi/Software/PKUAutoElective/autoelective/loop.py", line 380, in run_elective_loop
    captcha = recognizer.recognize(r.content)
  File "/home/poi/Software/PKUAutoElective/autoelective/captcha/recognizer.py", line 101, in recognize
    code = ''.join( self._model.LABELS[ix] for ix in ylist.argmax(axis=1) )
TypeError: argmax() got an unexpected keyword argument 'axis'

**Comment by zhongxinghong** [comment]
给一下你的 numpy 和 pytorch 版本，好像是 API 不兼容

**Comment by SkyDec** [comment]
我这里是 torch 版本不一样，亲测将 recognizer.py 的 102 行改成
`        code = ''.join( self._model.LABELS[ix] for ix in torch.argmax(ylist,dim=1))
`
就行了

**Comment by Poiw** [comment]
torch 1.1.0
numpy 1.18.0
好像的确是torch版本不匹配....我再去试试

**Comment by zhongxinghong** [comment]
懂了... 是它把 axis 换成 dim 了 ... 我去调一下这个兼容性 :( 各位稍等一下 ...

**Comment by zhongxinghong** [comment]
不对好像不是这样的 orz ... 还是等我一下吧我去研究一下为啥 ...

**Comment by Poiw** [comment]
换成dim我的就work了

**Comment by zhongxinghong** [comment]
> 我这里是 torch 版本不一样，亲测将 recognizer.py 的 102 行改成
> ` code = ''.join( self._model.LABELS[ix] for ix in torch.argmax(ylist,dim=1))`
> 就行了

我刚刚找朋友试了一下，这个方法确实可以解决这个问题，所以我现在把它更新到 v3.0.4 了，可以试试看 :) 我待会儿再去仔细研究一下这个 API 的兼容问题出在哪里

**Comment by zhongxinghong** [comment]
还是不调查了 :) axis 好像本身就不是 pytorch 的标准参数，以后记得用 dim 就好了 ...
