### ISSUE TITLE
NO TASKS

### ISSUE THREAD

**Issue by leetor** [zhongxinghong/PKUAutoElective#18]
### Check List

- [ ] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [ ] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ ] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [ ] \( run `python3 --version` )
AutoElective version: [ ] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置

### Issue Description
没有任务列表
#### What

[INFO] loop, 12:14:52, #--------------------------------------------#
[INFO] loop, 12:14:52, # PKU Auto-Elective Tool v3.0.4 (2020.02.17) #
[INFO] loop, 12:14:52, #--------------------------------------------#
[INFO] loop, 12:14:52,
[INFO] loop, 12:14:52,
[INFO] loop, 12:14:52, ======== Loop 1 ========
[INFO] loop, 12:14:52,
[INFO] loop, 12:14:52, No tasks
[INFO] loop, 12:14:52, Quit elective loop
[INFO] loop, 12:14:52, Quit IAAA loop

CONFIG 设置
# filename: config.ini
# coding: utf-8

[user]

; student_id    string    学号
; password      string    密码
; dual_degree   boolean   是否为双学位账号，可选 (true, false, True, False, 1, 0)
;                           住：只要你的账号在登录时需要选择 "主修/辅双" 身份，此处就需要设为 true
; identity      string    双学位账号登录身份，可选 ("bzx","bfx") 对应于 "主修/辅双"

student_id = XXXXXXXXX
password = XXXXXXXXX
dual_degree = false
identity = bzx

[client]

; supply_cancel_page           int       待刷课程处在选课计划的第几页
; refresh_interval             float     每次循环后的暂停时间，单位 s
; random_deviation             float     偏移量分数，如果设置为 <= 0 的值，则视为 0
; iaaa_client_timeout          float     IAAA 客户端最长请求超时
; elective_client_timeout      float     elective 客户端最长请求超时
; elective_client_pool_size    int       最多同时保持几个 elective 的有效会话（同一 IP 下最多为 5）
; login_loop_interval          float     IAAA 登录线程每回合结束后的等待时间
; debug_print_request          boolean   是否打印请求细节
; debug_dump_request           boolean   是否将重要接口的请求以日志的形式记录到本地（包括补退选页、提交选课等接口）
;
; 关于刷新间隔的配置示例:
;
; refresh_interval = 8
; random_deviation = 0.2
;
; 则每两个循环的间隔时间为 8 * (1.0 ± 0.2) s

supply_cancel_page = 1
refresh_interval = 8
random_deviation = 0.2
iaaa_client_timeout = 30
elective_client_timeout = 60
elective_client_pool_size = 3
login_loop_interval = 2
debug_print_request = false
debug_dump_request = false

[monitor]

; host   str
; port   int

host = 127.0.0.1
port = 7074

;---------------- course ----------------;
;
; 课程结构定义：
;
; [course:${id}]      ; 用户为该课程定义的 id
;
; name = ${name}      ; elective 中的 `课程名`
; class = ${class}    ; elective 中的 `课号`
; school = ${school}  ; elective 中的 `开课单位`
;
;
; 例如：
;
; [course:math_3]
;
; name = 集合论与图论
; class = 3
; school = 信息科学技术学院
;
; 可以解析出：
;
; id = "math_3"
; name = "集合论与图论"
; class = 3
; school = "信息科学技术学院"
;
;
; 更多例子：
;
; [course:db]
;
; name = 数据库概论
; class = 1
; school = 信息科学技术学院
;
; [course:0]
;
; name = 概率统计 （A）
; class = 1
; school = 信息科学技术学院
;
;
; 注意：
;
; 1. [course:${id}] 中可以带空格，但是不推荐
;      例如 [course: 1], [course:math 1] [ course : hello world ]
;      可以解析出: "1", "math 1", "hello world"
; 2. [course:${id}] 中不要带有 ',' 否则会在后续规则定义中引入混乱！ 不接受 '\,' 转义
;      例如 [course:Hai,Alice] 是非法的，在解析时会被忽略
; 3. [course:${id}] 中可以带有 ':'，但是不推荐
;
;----------------------------------------;

; [course:sb]
;
; name = 机器学习概论
; class = 1
; school = 信息科学技术学院

;---------------- mutex ----------------;
;
; 互斥规则结构定义：
;
; [mutex:${id}]                   ; 用户为该互斥规则定义的 id
;
; courses = ${cid1},${cid2},...   ; 用户定义的多个课程的 id，以 ',' 分隔
;
;
; 例如：
;
; [course:math_1]
;   ...
;
; [course:math_2]
;   ...
;
; [course:math_3]
;   ...
;
;
; [mutex:0]
;
; courses = math_1,math_2,math_3
;
; 可以解析出
;
; id = "0"
; courses = ["math_1", "math_2", "math_3"]
;
;
; 解释：
;
; 同一个互斥规则内的课程一旦有一门课已经被选上，其他课程将会被自动忽略。
; 例如，对于上述例子，如果 math_1, math_2, math_3 有任何一门课已经被选上，其它两门课将会被自动忽略
; 例如，当 math_1 被选上时，math_2, math_3 会被自动忽略
;
;
; 注意：
;
; 1. [mutex:${id}] 的命名注意事项同 course
; 2. courses 中可以有空格，但是不推荐
;      例如 courses = math_1, math_2  , math_3
;      仍可以解析出 ["math_1", "math_2", "math_3"]
;
;---------------------------------------;

; [mutex:sample]
;
; courses = course_id_1,course_id_2

**Comment by zhongxinghong** [comment]
; 开头表示那行是注释 ... 你把那个课前面的分号去掉就行了

**Comment by leetor** [comment]
抱歉，我的锅，我已经发现了，还有各问题是，用以前老版本的时候，在填验证码的时候一直重复填写 且validres=1
56:53, Recognition Result: iTw7
[WARNING] main, 12:56:53, Unknown validation result: 1
[INFO] main, 12:56:53, Get a captcha
[INFO] main, 12:56:53, Recognition Result: R2sN
[WARNING] main, 12:56:53, Unknown validation result: 1
[INFO] main, 12:56:53, Get a captcha
[INFO] main, 12:56:54, Recognition Result: ibbM
[WARNING] main, 12:56:54, Unknown validation result: 1
[INFO] main, 12:56:54, Get a captcha
[INFO] main, 12:56:54, Recognition Result: c8hr
[WARNING] main, 12:56:54, Unknown validation result: 1
[INFO] main, 12:56:54, Get a captcha
[INFO] main, 12:56:54, Recognition Result: aRFi
[WARNING] main, 12:56:54, Unknown validation result: 1
[INFO] main, 12:56:54, Get a captcha
[INFO] main, 12:56:54, Recognition Result: XmcR
[WARNING] main, 12:56:55, Unknown validation result: 1
[INFO] main, 12:56:55, Get a captcha
[INFO] main, 12:56:55, Recognition Result: 3Fbk
[WARNING] main, 12:56:55, Unknown validation result: 1
[INFO] main, 12:56:57, Get a captcha



看源码也不太清楚怎么改这里
def _task_validate_captcha(elective):
&nbsp; &nbsp; """ 填一次验证码 """
&nbsp; &nbsp; while True:
&nbsp; &nbsp; &nbsp; &nbsp; cout.info("Fetch a captcha")
&nbsp; &nbsp; &nbsp; &nbsp; r = elective.get_DrawServlet()
&nbsp; &nbsp; &nbsp; &nbsp; captcha = recognizer.recognize(r.content)
&nbsp; &nbsp; &nbsp; &nbsp; code = captcha.code
&nbsp; &nbsp; &nbsp; &nbsp; cout.info("Recognition result: %s" % code)


&nbsp; &nbsp; &nbsp; &nbsp; r = elective.get_Validate(code)
&nbsp; &nbsp; &nbsp; &nbsp; try:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; res = r.json()["valid"]&nbsp; # 可能会返回一个错误网页 ...
&nbsp; &nbsp; &nbsp; &nbsp; except Exception as e:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ferr.error(e)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; raise OperationFailedError(msg="Unable to validate captcha")


&nbsp; &nbsp; &nbsp; &nbsp; if res == "2":
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cout.info("Validation passed!")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; captcha.clear_cache()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cout.info("Clear captcha cache")
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; break
&nbsp; &nbsp; &nbsp; &nbsp; elif res == "0":
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cout.info("Validation failed, try again")
&nbsp; &nbsp; &nbsp; &nbsp; else:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; cout.warning("Unknown validation result: %s" % validRes)







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rabbit"<notifications@github.com&gt;; 
发送时间: 2020年2月17日(星期一) 中午12:54
收件人: "zhongxinghong/PKUAutoElective"<PKUAutoElective@noreply.github.com&gt;; 
抄送: "ξ→_→ξ"<1192855530@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [zhongxinghong/PKUAutoElective] NO TASKS (#18)




; 开头表示那行是注释 ... 你把那个课前面的分号去掉就行了

**Comment by zhongxinghong** [comment]
因为 elective 的 url 换了，具体为什么是 "1" 我也不清楚，但是应该和他的接口变更有关，你用 v3.0.3 以上的版本就可以
