### ISSUE TITLE
最后一步运行时出现故障

### ISSUE THREAD

**Issue by pivitol** [zhongxinghong/PKUAutoElective#19]
### Check List

- [x] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [ ] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ MacOS 10.13.6] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [ python3 --version] \( run `python3 --version` )
AutoElective version: [ run `main.py --version`] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置

#### What

遇到的问题

#### Console Log
Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: /Users/paul/Desktop/PKUAutoElective-ff035f740fe33859882d42857bca79dc5f595e70/main.py
Traceback (most recent call last):
  File "/Users/paul/Desktop/PKUAutoElective-ff035f740fe33859882d42857bca79dc5f595e70/main.py", line 10, in <module>
    from autoelective.environ import Environ
  File "/Users/paul/Desktop/PKUAutoElective-ff035f740fe33859882d42857bca79dc5f595e70/autoelective/environ.py", line 6, in <module>
    from .utils import Singleton
  File "/Users/paul/Desktop/PKUAutoElective-ff035f740fe33859882d42857bca79dc5f595e70/autoelective/utils.py", line 10, in <module>
    from requests.compat import json
ModuleNotFoundError: No module named 'requests'
在这一步停止了，计算机小白求问解决方案……

必要的终端输出信息

#### Reproduce

如有必要，提供复现的步骤

**Comment by zhongxinghong** [comment]
你的环境可能没有配对，你需要按照说明安装那些依赖包。在安装前你可以运行一下 `pip3 --version` 和 `python3 --version` 确保 pip 和 python 是对应的（如果你有多个 python 环境）

**Comment by pivitol** [comment]
> 你的环境可能没有配对，你需要按照说明安装那些依赖包。在安装前你可以运行一下 `pip3 --version` 和 `python3 --version` 确保 pip 和 python 是对应的（如果你有多个 python 环境）

好的，我试一下，感谢！！

**Comment by pivitol** [comment]
> 你的环境可能没有配对，你需要按照说明安装那些依赖包。在安装前你可以运行一下 `pip3 --version` 和 `python3 --version` 确保 pip 和 python 是对应的（如果你有多个 python 环境）

PauldeMacBook-Air:~ paul$ pip3 --version
pip 20.0.2 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
PauldeMacBook-Air:~ paul$ python3 --version
Python 3.8.1
应该是对应的啊……只有一个python环境

**Comment by zhongxinghong** [comment]
那你有用 pip3 安装过说明里的那些包吗 ... 你可以输 `pip3 list` 检查一下现在的包

**Comment by pivitol** [comment]
> 那你有用 pip3 安装过说明里的那些包吗 ... 你可以输 `pip3 list` 检查一下现在的包

Package     Version
----------- -------
numpy       1.18.1 
Pillow      7.0.0  
pip         20.0.2 
setuptools  41.2.0 
six         1.14.0 
torch       1.4.0  
torchvision 0.5.0  

都……都安装了QAQ

**Comment by Poiw** [comment]
pip3 install requests

**Comment by pivitol** [comment]
> pip3 install requests

果然！已经成功运行了！！谢谢！！
