### ISSUE TITLE
关于course的设置问题

### ISSUE THREAD

**Issue by MengXiangyu0624** [zhongxinghong/PKUAutoElective#20]
### Check List

- [ √] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [ √] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ ] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [ ] \( run `python3 --version` )
AutoElective version: [ ] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置

#### What

想问下大佬，courseId是指系统里的“”课程号“”吗？还是我随便设置一个就行。class是指系统里的班号还是课号呢。

; [course:${id}]      ; 用户为该课程定义的 id
;
; name = ${name}      ; elective 中的 `课程名`
; class = ${class}    ; elective 中的 `课号`
; school = ${school}  ; elective 中的 `开课单位`

#### Console Log

必要的终端输出信息

#### Reproduce

如有必要，提供复现的步骤

**Comment by zhongxinghong** [comment]
是指班号 1,2,3 班这样，不是课程号

因为一个院系开的一个课可能有多个班，所以这个 `班号` 用来区分每一个班
