### ISSUE TITLE
选课失败后会自动结束运行

### ISSUE THREAD

**Issue by Zuwak** [zhongxinghong/PKUAutoElective#21]
发现该问题的版本：2.1
具体状况：今天两次遇到2.1版本运行时未选到课却自动退出的问题。检查log发现可能由于选课网自身的问题，有时候某一门课程返回的选课人数是错误的，出现问题的课实际上是180/180，当时记录的html中却显示180/0，然后补选程序（获取到180/0后可能试图进行了补选操作）就自动退出了。

**Comment by zhongxinghong** [comment]
嗯，这个问题有不少人跟我反馈过，这个应该是选课网的某个 BUG，我觉得我可以做一个特殊适配，如果遇到已选为 0 就视为是选课网暂时的 BUG 而不代表课本身不能选上，然后一直尝试重新选课，等我明天有空的时候完善一下吧～

**Comment by zhongxinghong** [comment]
昨晚弄完忘了说了 ... 我昨天查了一下v2.1.x和v2.0.1，代码从逻辑上应该不会出现遇到 180/0 就自动退出的问题。我的设定里，应该只有几种特定情况会退出的，对于这种未知的错误，程序会默认继续工作。如果你的程序在遇到这种错误的时候就自动退出，那我可能需要了解一些更具体的情况，因为我并不希望程序有这个表现。昨晚我改了一版，现在遇到 180/0 这种情况程序可以给出更加明确的输出，而不是一个 unknown tips 了

**Comment by Zuwak** [comment]
之前应该是我弄错了，程序可能没有退出，可能只是monitor被关闭了。因为我把程序挂在服务器后台用反向代理，当时看到那个端口关闭了就以为是程序自动退出
