### ISSUE TITLE
课程名中有必要包括「(重修)」字样吗？

### ISSUE THREAD

**Issue by IceCodeNew** [zhongxinghong/PKUAutoElective#22]
### Check List

- [x] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [x] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [Ubuntu 18.04.4 amd64] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [3.7.5] \( run `python3 --version` )
AutoElective version: [3.0.5] \( run `python3 main.py --version` )

#### What

课程名中有必要包括「(重修)」字样吗？

**Comment by IceCodeNew** [comment]
好了，实际跑起来就知道答案了——要带上（

**Comment by zhongxinghong** [comment]
你的补选页选课列表里写的是什么你就填什么上去就可以了，程序是解析那个页面然后用 str.__eq__ 匹配的，必须要完全一样才行 :) 然后如果你填的课不存在会报错的
