### ISSUE TITLE
OperationFailedError encountered 疑似验证码出现错误？

### ISSUE THREAD

**Issue by zdhNarsil** [zhongxinghong/PKUAutoElective#23]
### Check List

- [ ] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [ ] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ MacOS 10.14.6] 
Python version: [ 3.7.4] \( run `python3 --version` )
AutoElective version: [2.11 ] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置
dual_degree = false
identity = bzx

supply_cancel_page = 1
refresh_interval = 3
random_deviation = 0.2
iaaa_client_timeout = 30
elective_client_timeout = 60
elective_client_pool_size = 5
login_loop_interval = 2
debug_print_request = false
debug_dump_request = false
#### What

遇到的问题
[WARNING] loop, 22:22:44, Unknown validation result: 1
[INFO] loop, 22:22:44, Fetch a captcha
[INFO] loop, 22:22:44, Recognition result: GMNp

必要的终端输出信息

#### Console Log[ERROR] loop.error, 22:22:53, Expecting value: line 5 column 1 (char 8)
[ERROR] loop.error, 22:22:53, [103] Unable to validate captcha
[WARNING] loop, 22:22:53, OperationFailedError encountered

#### Reproduce

如有必要，提供复现的步骤

**Comment by zhongxinghong** [comment]
v2.x.x 的验证码接口有问题，不要用了，换 v3.0.3 以上的版本吧 ... v2.x.x 的验证确实会出这个问题

**Comment by zhongxinghong** [comment]
因为今天早上选课网更新了一波接口，所以 v2.x.x 的几个 API 已经失效了
