### ISSUE TITLE
无法正常使用monitor

### ISSUE THREAD

**Issue by moulai** [zhongxinghong/PKUAutoElective#24]
添加-m属性后，没有设置nginx反代，直接本地浏览器查看127.0.0.1:7074，显示“无法访问此网站”，但是查看log，的确有”running on http://127.0.0.1:7074“，请问是什么原因？

**Comment by zhongxinghong** [comment]
这个问题我也不是很确定 ... 我也重复不出来 ... 如果让我猜测可能的原因的话 

1. 防火墙没有打开 7074 端口（但是本地应该没问题）
2. 7074 端口已经被占用（但是 flask 应该会不能正常启动）
3. 浏览器坑你（试一下换个浏览器，比如 Chrome，或者试一下 curl 之类的命令）
4. 试一下 `http://127.0.0.1:7074/` （werkzeug 版本差异引起 strict_slashes 的默认值不同？但是这个需要）
5. 试一下 `http://127.0.0.1:7074/stat` 这种非 `/` 的路由

**Comment by moulai** [comment]
已经解决问题，在linux服务器端的host不能设置成127.0.0.1，设置成0.0.0.0就可以正常访问了。谢谢！

**Comment by zhongxinghong** [comment]
讲真的 linux 服务器我是可以用 127.0.0.1 的 :) ... 可能你可以去想一下为什么 127.0.0.1 不能用 ...
