### ISSUE TITLE
似乎显示Quit IAAA loop后就卡住了

### ISSUE THREAD

**Issue by Newbeeer** [zhongxinghong/PKUAutoElective#26]
Hi,

我按照您的README配置好，开跑后显示:

No tasks,
Quit elective loop
Quit IAAA loop,
然后卡住了。请问这个问题怎么解决呢？感谢

**Comment by Newbeeer** [comment]
我查了下是直接卡在了main.py的78行Queue().get()那边

**Comment by Newbeeer** [comment]
I think I fix the bug. Thanks!

**Comment by wwk510** [comment]
> I think I fix the bug. Thanks!

请问是如何解决的，遇到相同的问题了

**Comment by Newbeeer** [comment]
我是[course:xxx]那边格式弄错了(貌似pycharm编辑这个不太方便），貌似要根据.ini文件的格式来写，我直接复制上面的[monitor]下来然后把方框里的改了就行。你也可以python3 main.py -m看看报错原因

**Comment by Newbeeer** [comment]
就是[...]代表section的意思，但是不知道咋回事在Pycharm里自己输入就没这个效果

**Comment by wwk510** [comment]
> 就是[...]代表section的意思，但是不知道咋回事在Pycharm里自己输入就没这个效果

明白了 谢谢！

**Comment by zhongxinghong** [comment]
你看到 Quit 就表示它正常退出了 ... 我懒得再写 Event 之类的东西了，直接 `Ctrl + C` 就可以 :)
