### ISSUE TITLE
请问能增加“退选”功能吗？

### ISSUE THREAD

**Issue by moulai** [zhongxinghong/PKUAutoElective#28]
比如我想选课号为12的毛概课，但是由于这个课非常火爆，只能先选上课号13的毛概（免得最后没有毛概上），这两门课的时间是一模一样的。能否增加一个“推选”功能，在检测到A课程有空位时，自动退掉设置好的B课程，并选上A课程？
非常感谢！

**Comment by zhongxinghong** [comment]
按照现在用户量，退课的这个间隙可能刚刚刷出来的空位就没了 :( Python 的刷课机完全无法阻止用户使用极端的刷新间隔 ... 我现在也不清楚大众的刷新间隔已经到哪个数量级了 orz ... 所以我不是很敢添加这样的功能 ... 这个问题在 #8 里有类似地讨论过

如果你想要这样的功能的话，还是推荐你 fork 一版然后自己开发 :)

我个人的看法是，有课上就行了 :) ...... 先确保能有课上 (至少能毕业 ;-) ，至于是不是最好的课，我个人就不是很追求了 :)

**Comment by moulai** [comment]
那请问是否能加入，某个课程，达到设定人数的阈值，就选上？还是上述情况，我先手动退掉B课程，正常刷A课程。但是当B课程达到例如78/80的情况时，就把B课程选上，以免无课课上？这样既不会有退课的时间差，又不用担心连B课程都选不上……（真实困境）不好意思，打扰了哈

**Comment by moulai** [comment]
不过感觉这个需求还是比较小众Orzzzz

**Comment by zhongxinghong** [comment]
这个倒是可以帮你实现一下，按照现在的架构这个实现起来还是比较容易的 :) 等下一版吧，做好了告诉你

**Comment by zhongxinghong** [comment]
我在 v3.0.8 中实现了你想要的功能，你可以了解一下 :) 记得仔细看手册

**Comment by moulai** [comment]
非常感谢您！
