### ISSUE TITLE
关于Ignored Tasks中可能存在的逻辑问题

### ISSUE THREAD

**Issue by Admittedly-Goat** [zhongxinghong/PKUAutoElective#29]
两个现象：1、按照学校规定，在2/21,15:00时会开放跨院系选课
2、您的程序会把没到跨院系选课时间的课程扔进Ignored Tasks里
一个假设：如果有人在2/21,14:59开启了刷课机，但是程序检测到没到跨院系选课的时间，把这门课扔进了Ignored Tasks里，这会不会导致错过课程的空缺名额呢

**Comment by drizmiz** [comment]
查看选课网帮助，会发现那时候是系统维护时间，所以这个问题事实上是不存在的

**Comment by zhongxinghong** [comment]
> 查看选课网帮助，会发现那时候是系统维护时间，所以这个问题事实上是不存在的

这个说法是对的 :) 这个事情我亲身经历过
