### ISSUE TITLE
听树洞说不少刷课机把自己的课退了，想问频率控制在多少比较合适呢

### ISSUE THREAD

**Issue by pivitol** [zhongxinghong/PKUAutoElective#31]
听树洞说不少刷课机把自己的课退了，想问频率控制在多少比较合适呢……
### Check List

- [ ] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [ ] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ ] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [ ] \( run `python3 --version` )
AutoElective version: [ ] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置

#### What

遇到的问题

#### Console Log

必要的终端输出信息

#### Reproduce

如有必要，提供复现的步骤

**Comment by zhongxinghong** [comment]
我不确定所谓的退课是否和刷新频率有关，但是抛开可能的 BUG 不谈，刷新频率本身就不能过高，否则可能会让选课网服务器压力过大，在爬虫界，疯狂请求对方服务器是一种很缺德的行为，即使对方没有提供 `robots.txt` 也不可以用诸如 `interval = 0` 之类的配置。对于频率控制最低不能小于多少，我并没有一个准确的说法，但是我给的默认间隔是 **8s**。代码是开源的，我无法阻止用户使用极端的刷新间隔，我只能建议你不要使用过低的刷新间隔

此外我在新版的 v3.0.9 里对可能发生的退课情况添加了一些防护，如果你担心程序会把你的课退了，你可以使用最新版。如果这种情况真的发生了，程序会自动中断，到时候你可以再给我发 Issue
