### ISSUE TITLE
无法登陆IAAA

### ISSUE THREAD

**Issue by AdyeshachOwO** [zhongxinghong/PKUAutoElective#35]
### Check List

- [x] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [x] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [MacOS 10.15.5 ] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [ 3.7.6] \( run `python3 --version` )
AutoElective version: [ 3.0.9] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置

dual_degree = false
identity = bzx

supply_cancel_page = 1
refresh_interval = 5
random_deviation = 0.1786
iaaa_client_timeout = 30
elective_client_timeout = 60
elective_client_pool_size = 3
login_loop_interval = 1
debug_print_request = false
debug_dump_request = false

host = 127.0.0.1
port = 7074

name = 马克思主义基本原理概论
class = 1
school = 马克思主义学院

#### What

遇到的问题

无法登陆IAAA

#### Console Log

必要的终端输出信息

~/PKUAutoElective$ python main.py
[INFO] loop, 09:05:18, #--------------------------------------------#
[INFO] loop, 09:05:18, # PKU Auto-Elective Tool v3.0.9 (2020.02.20) #
[INFO] loop, 09:05:18, #--------------------------------------------#
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, ======== Loop 1 ========
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, > Current tasks
[INFO] loop, 09:05:18, ------------------------------
[INFO] loop, 09:05:18, 01. Course(马克思主义基本原理概论, 1, 马克思主义学院)
[INFO] loop, 09:05:18, ------------------------------
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, > Current client: 1, (qsize: 3)
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, client: 1 needs Login
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, Try to login IAAA (client: 1)
[INFO] loop, 09:05:18, ======== END Loop 1 ========
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, ======== Loop 2 ========
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, > Current tasks
[INFO] loop, 09:05:18, ------------------------------
[INFO] loop, 09:05:18, 01. Course(马克思主义基本原理概论, 1, 马克思主义学院)
[INFO] loop, 09:05:18, ------------------------------
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, > Current client: 2, (qsize: 2)
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, client: 2 needs Login
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, ======== END Loop 2 ========
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, ======== Loop 3 ========
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, > Current tasks
[INFO] loop, 09:05:18, ------------------------------
[INFO] loop, 09:05:18, 01. Course(马克思主义基本原理概论, 1, 马克思主义学院)
[INFO] loop, 09:05:18, ------------------------------
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, > Current client: 3, (qsize: 1)
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, client: 3 needs Login
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, ======== END Loop 3 ========
[INFO] loop, 09:05:18, 
[ERROR] loop.error, 09:05:18, [102] 102. response status_code: 500
[WARNING] loop, 09:05:18, ServerError/StatusCodeError encountered
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:18, IAAA login loop sleep 1.0 s
[INFO] loop, 09:05:18, 
[INFO] loop, 09:05:19, Try to login IAAA (client: 1)
[ERROR] loop.error, 09:05:20, [102] 102. response status_code: 500
[WARNING] loop, 09:05:20, ServerError/StatusCodeError encountered
[INFO] loop, 09:05:20, 
[INFO] loop, 09:05:20, IAAA login loop sleep 1.0 s
[INFO] loop, 09:05:20, 
[INFO] loop, 09:05:21, Try to login IAAA (client: 1)
[ERROR] loop.error, 09:05:21, [102] 102. response status_code: 500
[WARNING] loop, 09:05:21, ServerError/StatusCodeError encountered
[INFO] loop, 09:05:21, 
[INFO] loop, 09:05:21, IAAA login loop sleep 1.0 s
[INFO] loop, 09:05:21, 
[INFO] loop, 09:05:22, Try to login IAAA (client: 1)
[ERROR] loop.error, 09:05:22, [102] 102. response status_code: 500
[WARNING] loop, 09:05:22, ServerError/StatusCodeError encountered
[INFO] loop, 09:05:22, 
[INFO] loop, 09:05:22, IAAA login loop sleep 1.0 s
[INFO] loop, 09:05:22, 
^Z
[3]+  Stopped                 python main.py

#### Reproduce

如有必要，提供复现的步骤

**Comment by webber900114** [comment]
我这也有一样的问题 是暑校系统的关系吗

**Comment by Constantine-12** [comment]
我也

**Comment by r-ram123** [comment]
我也遇到了同样的问题

**Comment by Catalyst0306** [comment]
我也

**Comment by Catalyst0306** [comment]
好像是ssoLogin失效了，而且iaaa给的提示是“请从应用系统访问身份认证系统。

**Comment by AdyeshachOwO** [comment]
> 好像是ssoLogin失效了，而且iaaa给的提示是“请从应用系统访问身份认证系统。

所以……有什么解决办法嘛

**Comment by Accelerator12919** [comment]
同无法登陆iaaa

**Comment by UteLar** [comment]
我这边也是

**Comment by yabukota** [comment]
一样。。。

**Comment by jy5275** [comment]
https://github.com/jy5275/PKUAutoElective 暂时解决了以上问题，姑且能用，尽管非常不graceful

**Comment by AdyeshachOwO** [comment]
> https://github.com/jy5275/PKUAutoElective 暂时解决了以上问题，姑且能用，尽管非常不graceful

报了 [310] 您尚未登录或者会话超时,请重新登录。

**Comment by AdyeshachOwO** [comment]
> https://github.com/jy5275/PKUAutoElective 暂时解决了以上问题，姑且能用，尽管非常不graceful

啊 没问题了 我配置没调好

**Comment by zhongxinghong** [comment]
各位久等了，我前面在赶 ddl 所以没空修 ... 

我参照这个方案发了新版 4.0.1

> https://github.com/jy5275/PKUAutoElective 暂时解决了以上问题，姑且能用，尽管非常不graceful

报 500 错误是因为现在 IAAA 登录需要携带有效 Cookies 了，现在我先让 IAAA 客户端请求一次 elective 的主页，这会设置 Cookies，然后再调 IAAA 的登录接口就没有问题了

**Comment by AdyeshachOwO** [comment]
> 各位久等了，我前面在赶 ddl 所以没空修 ...
> 
> 我参照这个方案发了新版 4.0.1
> 
> > https://github.com/jy5275/PKUAutoElective 暂时解决了以上问题，姑且能用，尽管非常不graceful
> 
> 报 500 错误是因为现在 IAAA 登录需要携带有效 Cookies 了，现在我先让 IAAA 客户端请求一次 elective 的主页，这会设置 Cookies，然后再调 IAAA 的登录接口就没有问题了

dalao辛苦了！十分感谢！
