### ISSUE TITLE
对二次验证OTP的支持

### ISSUE THREAD

**Issue by hayschan** [zhongxinghong/PKUAutoElective#40]
### Check List

- [ ☑️] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [☑️ ] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [macOS 10.15.6 ] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [Python 3.8.5] \( run `python3 --version` )
AutoElective version: [ ] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置

#### What

在portal打开了需要OTP才能登入，就会丢出下面的错误。把OTP关了，就没这个问题了。

#### Console Log

`[ERROR] loop.error, 10:00:40, [210] 210. response JSON: {'success': False, 'errors': {'code': 'E99', 'msg': 'Service with exception.'}, 'message': 'Operation FAIL.', 'rows': []}`

#### Reproduce

如有必要，提供复现的步骤

**Comment by zhongxinghong** [comment]
很难支持OTP，因为输入OTP这步需要人工操作，没法实现全自动化，没法做到任何时候掉线都能自动重登

这段时间暂时先关掉OTP吧 :)
