### ISSUE TITLE
提示课程不在选课计划中

### ISSUE THREAD

**Issue by GeorgeMLP** [zhongxinghong/PKUAutoElective#42]
### Check List

- 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ Windows10 64bit ]
Python version: [ python 3.8 ]
AutoElective version: [ v4.0.1 ]

### Config

[client]

supply_cancel_page = 1
refresh_interval = 8
random_deviation = 0.2
iaaa_client_timeout = 30
elective_client_timeout = 60
elective_client_pool_size = 3
login_loop_interval = 2
debug_print_request = false
debug_dump_request = false

[monitor]

[course:lxxt]

name = 力学B类习题补充
class = 3
school = 信息科学技术学院

[course:dbq1]

name = 地板球
class = 1
school = 体育教研部

[course:dbq2]

name = 地板球
class = 2
school = 体育教研部

[course:tjq1]

name = 太极拳
class = 4
school = 体育教研部

[course:tjq2]

name = 太极拳
class = 3
school = 体育教研部

[course:tjq3]

name = 太极拳
class = 16
school = 体育教研部

[course:tjq4]

name = 太极拳
class = 2
school = 体育教研部

[course:tjq5]

name = 太极拳
class = 19
school = 体育教研部

[course:tjq6]

name = 太极拳
class = 20
school = 体育教研部

[course:tjq7]

name = 太极拳
class = 21
school = 体育教研部

[course:dyyys]

name = 导引与养生
class = 1
school = 体育教研部

#### What

地板球、太极拳、导引与养生这三门课程都在我的选课计划的第一页，但程序提示 "Course(XXX, X, XXXXX) is not in your course plan, please check your config." 我的 config 中的其他体育课都能正常刷课（如棒、垒球、汉字太极与养生课、体适能），但这三门课程不行，要把它们注释掉才能正常刷别的课。
![image](https://user-images.githubusercontent.com/71643396/93765385-5f4d4b00-fc47-11ea-90bb-dbb2ba80add5.png)

#### Console Log

[INFO] loop, 19:54:23, #--------------------------------------------#
[INFO] loop, 19:54:23, # PKU Auto-Elective Tool v4.0.1 (2020.05.30) #
[INFO] loop, 19:54:23, #--------------------------------------------#
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, ======== Loop 1 ========
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, > Current tasks
[INFO] loop, 19:54:23, ------------------------------
[INFO] loop, 19:54:23, 01. Course(力学B类习题补充, 3, 信息科学技术学院)
[INFO] loop, 19:54:23, 02. Course(地板球, 1, 体育教研部)
[INFO] loop, 19:54:23, ------------------------------
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, > Current client: 1, (qsize: 3)
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, client: 1 needs Login
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, Try to login IAAA (client: 1)
[INFO] loop, 19:54:23, ======== END Loop 1 ========
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, ======== Loop 2 ========
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, > Current tasks
[INFO] loop, 19:54:23, ------------------------------
[INFO] loop, 19:54:23, 01. Course(力学B类习题补充, 3, 信息科学技术学院)
[INFO] loop, 19:54:23, 02. Course(地板球, 1, 体育教研部)
[INFO] loop, 19:54:23, ------------------------------
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, > Current client: 2, (qsize: 2)
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, client: 2 needs Login
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, ======== END Loop 2 ========
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, ======== Loop 3 ========
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, > Current tasks
[INFO] loop, 19:54:23, ------------------------------
[INFO] loop, 19:54:23, 01. Course(力学B类习题补充, 3, 信息科学技术学院)
[INFO] loop, 19:54:23, 02. Course(地板球, 1, 体育教研部)
[INFO] loop, 19:54:23, ------------------------------
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, > Current client: 3, (qsize: 1)
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, client: 3 needs Login
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:23, ======== END Loop 3 ========
[INFO] loop, 19:54:23,
[INFO] loop, 19:54:24, Login success (client: 1)
[INFO] loop, 19:54:24,
[INFO] loop, 19:54:24,
[INFO] loop, 19:54:24, IAAA login loop sleep 2.0 s
[INFO] loop, 19:54:24, ======== Loop 4 ========
[INFO] loop, 19:54:24,
[INFO] loop, 19:54:24,
[INFO] loop, 19:54:24, > Current tasks
[INFO] loop, 19:54:24, ------------------------------
[INFO] loop, 19:54:24, 01. Course(力学B类习题补充, 3, 信息科学技术学院)
[INFO] loop, 19:54:24, 02. Course(地板球, 1, 体育教研部)
[INFO] loop, 19:54:24, ------------------------------
[INFO] loop, 19:54:24,
[INFO] loop, 19:54:24, > Current client: 1, (qsize: 1)
[INFO] loop, 19:54:24,
[INFO] loop, 19:54:24, Get SupplyCancel page 1
[INFO] loop, 19:54:24, Get available courses
[ERROR] loop, 19:54:24, Course(地板球, 1, 体育教研部) is not in your course plan, please check your config.
[INFO] loop, 19:54:24,
[INFO] loop, 19:54:24, ======== END Loop 4 ========
[INFO] loop, 19:54:24, Main loop sleep 7.667335315068462 s
[INFO] loop, 19:54:24,
[INFO] loop, 19:54:26, Try to login IAAA (client: 2)
[INFO] loop, 19:54:26, Login success (client: 2)
[INFO] loop, 19:54:26,
[INFO] loop, 19:54:26, IAAA login loop sleep 2.0 s
[INFO] loop, 19:54:26,
[INFO] loop, 19:54:28, Try to login IAAA (client: 3)
[INFO] loop, 19:54:29, Login success (client: 3)
[INFO] loop, 19:54:29,
[INFO] loop, 19:54:29, IAAA login loop sleep 2.0 s
[INFO] loop, 19:54:29,
Exception in thread Elective:
Traceback (most recent call last):
  File "C:\Users\George M\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\George M\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\George M\PKUAutoElective-master\autoelective\loop.py", line 554, in run_elective_loop
    raise e
  File "C:\Users\George M\PKUAutoElective-master\autoelective\loop.py", line 393, in run_elective_loop
    raise UserInputException("%s is not in your course plan, please check your config." % c)
autoelective.exceptions.UserInputException: Course(地板球, 1, 体育教研部) is not in your course plan, please check your config.

#### Reproduce

如有必要，提供复现的步骤

**Comment by Yixuan-Wang** [comment]
README 似乎写错了，应该是在**补退选**的页数，而不是选课计划。

**Comment by GeorgeMLP** [comment]
谢谢！问题已经解决了，确实应该按照补退选的页数。
（不过 README 里似乎写的是 “确保它们处在选课计划列表的同一页” ）

![image](https://user-images.githubusercontent.com/71643396/93774975-7181b600-fc54-11ea-9626-c55236ff32db.png)

**Comment by zhongxinghong** [comment]
不好意思啦，这个我当时写得确实有些不清楚，我回头改一下 :)

**Comment by zhongxinghong** [comment]
V5.0.1 已经更新了相关描述
