### ISSUE TITLE
2.0.5版本Ctrl+C KeyboardInterrupt无法退出

### ISSUE THREAD

**Issue by cbwang2016** [zhongxinghong/PKUAutoElective#5]

**Comment by zhongxinghong** [comment]
不好意思 ... 最近这几版我只在 Linux 下测试过 ...

我查了一下资料，`Ctrl + C` 的行为在 Linux 和 Windows 下是不一致的，在 Windows 下 `Ctrl + C` 无法中断阻塞进程/线程，所以我现在用 `signal` 注册了一个额外的 `Ctrl + C handler` ，你可以试下 v2.0,6 这版，我在 win7 下测试是没问题的

另外你也可以试一下 `Ctrl + Break` ，这个我亲测在 v2.0.5 可用

#### References:

- [Stopping python using ctrl+c](https://stackoverflow.com/questions/1364173/stopping-python-using-ctrlc)
- [[Python-Dev] Interrupt thread.join() with Ctrl-C / KeyboardInterrupt on Windows](https://mail.python.org/pipermail/python-dev/2017-August/148800.html)
- [KeyboardInterrupt doesn't work when arcgisscripting module is loaded](https://gis.stackexchange.com/questions/2190/keyboardinterrupt-doesnt-work-when-arcgisscripting-module-is-loaded)

**Comment by cbwang2016** [comment]
2.0.6在我这Win10 pro 64位，Python 3.7.3下`Ctrl + C`仍然不行

**Comment by cbwang2016** [comment]
找到问题了，一会我Pull Request吧

**Comment by cbwang2016** [comment]
emmmm找到问题了但是不会修。。。
就是说`install_ctrl_c_handler`只在`task_run_loop_with_monitor`上加了，但是没有在`task_run_loop`上加。不过我试了一下，在`task_run_loop`加了好像也没用。。。

**Comment by cbwang2016** [comment]
不过问题不大，反正`Ctrl + Pause`一直可以用

**Comment by zhongxinghong** [comment]
等我晚上找人借个 Win10 64bit 系统试着弄一下 。。。`task_run_loop` 是非阻塞的进程，加了应该是没用的。我怀疑可能是因为 `run_main_loop` 里面的两个线程是阻塞的，然后没有办法中断 。。。不过要试一下才知道

**Comment by zhongxinghong** [comment]
@cbwang2016 Windows 的 signal 系统真的迷 。。。 我刚刚用了一个很诡异的方法修好了，但我也不知道为什么 :) 现在我已经在 Win7/Win10 下测过了，你可以试下这个 v2.0.8

**Comment by zhongxinghong** [comment]
我刚刚又改了一下，我发现只要子进程调用 join() 主进程就不能接收到来自 `Ctrl + C` 的信号，原来写的那个 `install_ctrl_c_handler` 其实一点用也没有 orz ... 所以我该用 `Queue.get` 直接阻塞主线程，然后就可以捕获到 `Ctrl + C` 了
