### ISSUE TITLE
新验证码是gif（动态验证码）了，请问程序如何识别？谢谢！！

### ISSUE THREAD

**Issue by KingOfDeBug** [zhongxinghong/PKUAutoElective#51]
### Check List

- [x] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [x] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ ] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [ ] \( run `python3 --version` )
AutoElective version: [ ] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置

#### What

遇到的问题

#### Console Log

必要的终端输出信息

#### Reproduce

如有必要，提供复现的步骤

**Comment by yiguanxianyu** [comment]
提供一个可能性：

我连续刷新了多次验证码，对每一张进行了拆分，发现完整的验证码总是出现在最后一帧上，或许可以先提取gif的最后一帧再进行验证码识别。

不过新版的验证码本身也变得更难识别了。

~~幸好我的课都没掉~~

**Comment by zhongxinghong** [comment]
等等吧 这几天看能不能做一个新模型
