### ISSUE TITLE
求问有没有哪位好心的大佬可以分享一下新验证码的训练集？方便大佬们各显神通训练模型^_^

### ISSUE THREAD

**Issue by KingOfDeBug** [zhongxinghong/PKUAutoElective#53]
### Check List

- [ ] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [ ] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ ] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [ ] \( run `python3 --version` )
AutoElective version: [ ] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置

#### What

遇到的问题

#### Console Log

必要的终端输出信息

#### Reproduce

如有必要，提供复现的步骤

**Comment by TheEighthDay** [comment]
不知道以前的验证码大小，我看代码里assert hight==22，模型训练的大小也是22，但是新的验证码130x52。不知道分割算法还work么？ @zhongxinghong

**Comment by zhongxinghong** [comment]
新版本发布了，数据集和模型都一并提供了
