### ISSUE TITLE
当补选不在第一页的课时会出现bug

### ISSUE THREAD

**Issue by Reno257** [zhongxinghong/PKUAutoElective#55]
### Check List

- [ ] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [x] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ ] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [ ] \( run `python3 --version` )
AutoElective version: [ ] \( run `python3 main.py --version` )

### Config

dual_degree = false
identity = bzx

supply_cancel_page = 4
refresh_interval = 5
random_deviation = 0.2
iaaa_client_timeout = 30
elective_client_timeout = 60
elective_client_pool_size = 2
elective_client_max_life = 600
login_loop_interval = 2
print_mutex_rules = true
debug_print_request = false
debug_dump_request = false

[course:ty]

name = 高尔夫
class = 1
school = 体育教研部

[course:ty2]

name = 体适能
class = 9
school = 体育教研部

[mutex:0]

courses = ty,ty2

[course:ss]

name = 死亡的社会学思考
class = 1
school = 社会学系

#### What

当补选不在第一页的课时会出现bug，而这些课确实是在相应的页数

#### Console Log

[INFO] loop, 11:17:33, #--------------------------------------------#
[INFO] loop, 11:17:33, # PKU Auto-Elective Tool v5.0.1 (2020.09.25) #
[INFO] loop, 11:17:33, #--------------------------------------------#
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > User Agent
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33, pool_size: 6402
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Config
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33, is_dual_degree: False
[INFO] loop, 11:17:33, identity: bzx
[INFO] loop, 11:17:33, refresh_interval: 5.0
[INFO] loop, 11:17:33, refresh_random_deviation: 0.2
[INFO] loop, 11:17:33, supply_cancel_page: 4
[INFO] loop, 11:17:33, iaaa_client_timeout: 30.0
[INFO] loop, 11:17:33, elective_client_timeout: 60.0
[INFO] loop, 11:17:33, login_loop_interval: 2.0
[INFO] loop, 11:17:33, elective_client_pool_size: 2
[INFO] loop, 11:17:33, elective_client_max_life: 600
[INFO] loop, 11:17:33, is_print_mutex_rules: True
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, ======== Loop 1 ========
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Current tasks
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33, 01. Course(高尔夫, 1, 体育教研部)
[INFO] loop, 11:17:33, 02. Course(体适能, 9, 体育教研部)
[INFO] loop, 11:17:33, 03. Course(死亡的社会学思考, 1, 社会学系)
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Mutex rules
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33, 01. Course(高尔夫, 1, 体育教研部) --x-- Course(体适能, 9, 体育教研部)
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Current client: 1 (qsize: 2)
[INFO] loop, 11:17:33, > Client expired time: -1
[INFO] loop, 11:17:33, User-Agent: Mozilla/5.0 (Linux; Android 9; MI 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.81 Mobile Safari/537.36
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, client: 1 needs Login
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, Try to login IAAA (client: 1)
[INFO] loop, 11:17:33, ======== END Loop 1 ========
[INFO] loop, 11:17:33, User-Agent: Mozilla/5.0 (Linux; Android 10; VOG-AL10 Build/HUAWEIVOG-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.62 XWEB/2691 MMWEBSDK/200801 Mobile Safari/537.36
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, ======== Loop 2 ========
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Current tasks
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33, 01. Course(高尔夫, 1, 体育教研部)
[INFO] loop, 11:17:33, 02. Course(体适能, 9, 体育教研部)
[INFO] loop, 11:17:33, 03. Course(死亡的社会学思考, 1, 社会学系)
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Mutex rules
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33, 01. Course(高尔夫, 1, 体育教研部) --x-- Course(体适能, 9, 体育教研部)
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Current client: 2 (qsize: 1)
[INFO] loop, 11:17:33, > Client expired time: -1
[INFO] loop, 11:17:33, User-Agent: Mozilla/5.0 (Linux; Android 10; YAL-AL10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.101 Mobile Safari/537.36
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, client: 2 needs Login
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, ======== END Loop 2 ========
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, Login success (client: 1, expired_time: 2021-03-07 11:27:33)
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, IAAA login loop sleep 2.0 s
[INFO] loop, 11:17:33, ======== Loop 3 ========
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Current tasks
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33, 01. Course(高尔夫, 1, 体育教研部)
[INFO] loop, 11:17:33, 02. Course(体适能, 9, 体育教研部)
[INFO] loop, 11:17:33, 03. Course(死亡的社会学思考, 1, 社会学系)
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Mutex rules
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33, 01. Course(高尔夫, 1, 体育教研部) --x-- Course(体适能, 9, 体育教研部)
[INFO] loop, 11:17:33, ------------------------------
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, > Current client: 1 (qsize: 1)
[INFO] loop, 11:17:33, > Client expired time: 2021-03-07 11:27:33
[INFO] loop, 11:17:33, User-Agent: Mozilla/5.0 (Linux; Android 10; VOG-AL10 Build/HUAWEIVOG-AL10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.62 XWEB/2691 MMWEBSDK/200801 Mobile Safari/537.36
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, Get Supplement page 4
[WARNING] loop, 11:17:33, IndexError encountered
[INFO] loop, 11:17:33, Get SupplyCancel first to prevent empty table returned
[INFO] loop, 11:17:33, Get Supplement page 4
[INFO] loop, 11:17:33, Get available courses
[ERROR] loop, 11:17:33, Course(高尔夫, 1, 体育教研部) is not in your course plan, please check your config.
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:33, ======== END Loop 3 ========
[INFO] loop, 11:17:33, Main loop sleep 4.011535216972663 s
[INFO] loop, 11:17:33,
[INFO] loop, 11:17:35, Try to login IAAA (client: 2)
[INFO] loop, 11:17:35, User-Agent: Mozilla/5.0 (Linux; Android 10; EML-AL00) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.81 Mobile Safari/537.36
[INFO] loop, 11:17:35, Login success (client: 2, expired_time: 2021-03-07 11:27:35)
[INFO] loop, 11:17:35,
[INFO] loop, 11:17:35,
[INFO] loop, 11:17:35, IAAA login loop sleep 2.0 s
[INFO] loop, 11:17:35,
Exception in thread Elective:
Traceback (most recent call last):
  File "D:\python\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "D:\python\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "D:\skj\autoelective\loop.py", line 631, in run_elective_loop
    raise e
  File "D:\skj\autoelective\loop.py", line 470, in run_elective_loop
    raise UserInputException("%s is not in your course plan, please check your config." % c)
autoelective.exceptions.UserInputException: Course(高尔夫, 1, 体育教研部) is not in your course plan, please check your config.

#### Reproduce

如有必要，提供复现的步骤

**Comment by PKUcshzy** [comment]
我今天上午也发现了这个问题,把课程换成第一页的就能够找到该课
(话说你是否方便交流一下刷课机的事情,我正在试图改,但我比较菜orz

**Comment by zhongxinghong** [comment]
#54
