### ISSUE TITLE
验证码

### ISSUE THREAD

**Issue by universefish** [zhongxinghong/PKUAutoElective#57]
### Check List

- [是 ] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [ 是] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ win 10] \( Windows10 64bit)
Python version: [ 3.7.0] \( run `python3 --version` )
AutoElective version: [ 最新的] \( run `python3 main.py --version` )

### Config

其余一律默认
[course:gsm_1]

name = 互联网与商业模式创新
class = 1
school = 光华管理学院

[course:test_1]

name = 名家专题讲座
class = 1
school = 经济学院

#### What

Autoelective 报错：
AssertionError: unexpected number of captcha blocks: 0
[INFO] loop,  Fetch a captcha
[ERROR] loop.error, unexpected number of captcha blocks: 0

#### Console Log

必要的终端输出信息

**Comment by ling23187** [comment]
新的验证码识别不了的啊

**Comment by zhongxinghong** [comment]
刚刚发布了新版本，可以识别了

**Comment by universefish** [comment]
谢谢
