### ISSUE TITLE
[ERROR] loop.error, 09:20:52, [310] 您尚未登录或者会话超时,请重新登录。

### ISSUE THREAD

**Issue by KingOfDeBug** [zhongxinghong/PKUAutoElective#62]
显示“您尚未登录或者会话超时,请重新登录。”应该是选课网api更新的结果，请问如何解决？

### Check List

- [x] 我已经阅读了 [Readme](https://github.com/zhongxinghong/PKUAutoElective/blob/master/README.md), [Migration Guide](https://github.com/zhongxinghong/PKUAutoElective/blob/master/MIGRATION_GUIDE.md), [Realease History](https://github.com/zhongxinghong/PKUAutoElective/blob/master/HISTORY.md) ，但是并没有找到有用的信息
- [x] 我已经搜索了已有的 [Issues](https://github.com/zhongxinghong/PKUAutoElective/issues) ，但是没有找到相同的问题

### Version / Environment

System infomation: [ ] \( Windows10 64bit, MacOS 10.13.6, Ubuntu 18.04.3 amd64, ... )
Python version: [ ] \( run `python3 --version` )
AutoElective version: [ ] \( run `python3 main.py --version` )

### Config

除了学号/密码外的其他配置

#### What

遇到的问题

#### Console Log

必要的终端输出信息

#### Reproduce

如有必要，提供复现的步骤

**Comment by webber900114** [comment]
同问题

**Comment by xiaotianxt** [comment]
同问题

**Comment by xiaotianxt** [comment]
临时解决方案:
`autoelective/const.py`, line66, 在网址末尾处加上`?xh=1x000xxxxx`(个人学号)
```python
SupplyCancel = "https://elective.pku.edu.cn/elective2008/edu/pku/stu/elective/controller/supplement/SupplyCancel.do?xh=1x000xxxxx"

```

**Comment by webber900114** [comment]
It works. Thank you!
