### ISSUE TITLE
【fork宣传】针对2021年秋季学期选课网API的升级 (beta)

### ISSUE THREAD

**Issue by Chiyun-CHU** [zhongxinghong/PKUAutoElective#65]
2021年秋季学期选课网修改了SupplyCancel.do的逻辑，必须以SupplyCancel.do?xh=的形式进行请求。
除此之外，在补退选第一阶段的候补选课中试了一下，没有发现别的改动。
这一变化非常小，以至于我这种代码水平都可以撸出来，就几行的变动，没啥技术含量，但为了方便还是fork了，把自己的改动传了上来。
按照Rabbit的要求，并没有进行clone，直接搜搜不到，因此就来Issues里面宣传一下。
算是个beta版，不确定补退选第二阶段能不能完全work，到时候再看着改吧。
https://github.com/Chiyun-CHU/PKUAutoElective_updated

**Comment by dandaopitiao** [comment]
请问dl，我这边一直报ERROR您尚未登录或者会话超时,请重新登录。这个应该怎么解决呀，是不是又被ban了orz

**Comment by Chiyun-CHU** [comment]
> 请问dl，我这边一直报ERROR您尚未登录或者会话超时,请重新登录。这个应该怎么解决呀，是不是又被ban了orz

emm如果你是在我的fork下clone的项目，应该不会有这个问题啊……我改代码就是为了解决这个ERROR，这就是上面说的直接请求SupplyCancel.do的结果……如果你实在Rabbit这边clone的，那一定是会报这个错的。
以及刚刚试验了一下，一切正常，选课也没有问题。还是得感谢@Rabbit, @xmcp, @SpiritedAwayCN, @gzz他们训练的神经网络……我自己根本对付不了这些验证码orz。

**Comment by dandaopitiao** [comment]
嗯嗯，是在您的fork下进行的，但是一直会报这个错orz，那是我这边有什么问题嘛…

**Comment by SpiritedAwayCN** [comment]
> 请问dl，我这边一直报ERROR您尚未登录或者会话超时,请重新登录。这个应该怎么解决呀，是不是又被ban了orz

准确来说就是补退选API更新之后就是URL中多了一个xh=<学号>，听描述应该这里修改得没问题

**Comment by dandaopitiao** [comment]
我这边还是一直会报这个错误，想请问两位大佬我应该怎么办啊呜呜

**Comment by Chiyun-CHU** [comment]
> 嗯嗯，是在您的fork下进行的，但是一直会报这个错orz，那是我这边有什么问题嘛…

emm不应该啊……学一下微软客服鸟用没有的帮助支持意见，您可以试试：

* 重新配置PKUAutoElective
* 找一个正常的config.ini测试一下
* 换台电脑或者换个网络环境试一试

这种情况可能就真的和您说的一样被ban了IP，也有一定可能是config.ini没写好……真的不好确定，只能自己排查。

如果您是研究生的话，研究生选课我还没有测试。假设研究生的SupplyCancel.do逻辑不一样，那我恐怕一时半会解决不了了……

**Comment by SpiritedAwayCN** [comment]
> > 嗯嗯，是在您的fork下进行的，但是一直会报这个错orz，那是我这边有什么问题嘛…
> 
> emm不应该啊……学一下微软客服鸟用没有的帮助支持意见，您可以试试：
> 
> * 重新配置PKUAutoElective
> * 找一个正常的config.ini测试一下
> * 换台电脑或者换个网络环境试一试
> 
> 这种情况可能就真的和您说的一样被ban了IP，也有一定可能是config.ini没写好……真的不好确定，只能自己排查。
> 
> 如果您是研究生的话，研究生选课我还没有测试。假设研究生的SupplyCancel.do逻辑不一样，那我恐怕一时半会解决不了了……

另外翻阅了一下您的代码，`elective.py`第151行这种加参数的写法不太推荐：
`url=ElectiveURL.SupplyCancel+"?xh="+str(username)`

建议使用类似：
```
r = self._get(
            url=ElectiveURL.SupplyCancel,
            headers=headers,
            hooks=_hooks_check_title,
            params={"xh": username}
        )
```
之类的写法，可能会稳定一些（万一出现什么奇怪的URL）

**Comment by pkuqpython** [comment]
谢谢作者~

**Comment by pkuqpython** [comment]
> 我这边还是一直会报这个错误，想请问两位大佬我应该怎么办啊呜呜

如果是双学位但没有先设置好的话，会报这个错。

**Comment by Chiyun-CHU** [comment]
> > > 嗯嗯，是在您的fork下进行的，但是一直会报这个错orz，那是我这边有什么问题嘛…
> > 
> > 
> > emm不应该啊……学一下微软客服鸟用没有的帮助支持意见，您可以试试：
> > 
> > * 重新配置PKUAutoElective
> > * 找一个正常的config.ini测试一下
> > * 换台电脑或者换个网络环境试一试
> > 
> > 这种情况可能就真的和您说的一样被ban了IP，也有一定可能是config.ini没写好……真的不好确定，只能自己排查。
> > 如果您是研究生的话，研究生选课我还没有测试。假设研究生的SupplyCancel.do逻辑不一样，那我恐怕一时半会解决不了了……
> 
> 另外翻阅了一下您的代码，`elective.py`第151行这种加参数的写法不太推荐：
> `url=ElectiveURL.SupplyCancel+"?xh="+str(username)`
> 
> 建议使用类似：
> 
> ```
> r = self._get(
>             url=ElectiveURL.SupplyCancel,
>             headers=headers,
>             hooks=_hooks_check_title,
>             params={"xh": username}
>         )
> ```
> 
> 之类的写法，可能会稳定一些（万一出现什么奇怪的URL）

感谢提醒，我过两天闲下来后把代码改一下。当时因为补退选第一阶段测试时间紧，本着能用就行的心态码的……确实要改，不然一两个学期下来代码就是一团乱麻了……

**Comment by ry12138** [comment]
dl您好，我想请问一下运行了main.py之后只有loop1就不接着运行了，应该怎么办呀呜呜

**Comment by Chiyun-CHU** [comment]
> dl您好，我想请问一下运行了main.py之后只有loop1就不接着运行了，应该怎么办呀呜呜

可能性太多了，不把输出发出来真没法排查，但把输出发出来又不太合适，起码可以知道你狙的是什么课……

只能说大概率是config.ini的配置问题，认真读一下注释，尤其是注意要指定页数，而且课程信息不能填错……或者找一个成功了的config.ini对着比较一下吧……

**Comment by Hubertzhangyh** [comment]
[ERROR] loop.error, 14:04:53, HTTPSConnectionPool(host='iaaa.pku.edu.cn', port=443): Max retries exceeded with url: /iaaa/oauth.jsp?appID=syllabus&appName=%E5%AD%A6%E7%94%9F%E9%80%89%E8%AF%BE%E7%B3%BB%E7%BB%9F&redirectUrl=http%3A%2F%2Felective.pku.edu.cn%3A80%2Felective2008%2FssoLogin.do (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
[WARNING] loop, 14:04:53, RequestException encountered
请问是什么原因呢……

**Comment by CinnabarCHU** [comment]
> [ERROR] loop.error, 14:04:53, HTTPSConnectionPool(host='iaaa.pku.edu.cn', port=443): Max retries exceeded with url: /iaaa/oauth.jsp?appID=syllabus&appName=%E5%AD%A6%E7%94%9F%E9%80%89%E8%AF%BE%E7%B3%BB%E7%BB%9F&redirectUrl=http%3A%2F%2Felective.pku.edu.cn%3A80%2Felective2008%2FssoLogin.do (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1122)')))
> [WARNING] loop, 14:04:53, RequestException encountered
> 请问是什么原因呢……

抱歉有些事情耽误了，这个应该不是程序本身的问题了，更像是IP被ban了或者网络设置有问题，或者已经有同学和你公用校内网IP开刷了……换个网络环境吧。

**Comment by CinnabarCHU** [comment]
以及@Rabbit已经merge了来自@lhydave和@Guyutongxue的pull，直接下载zhongxinghong/PKUAutoElective的master分支就可以使用了，两位大佬的代码实现比我的方法要稳定的多，尤其是@Guyutongxue帮人找bug的能力不减当年啊……当时知道自己的代码比较不稳定，以及为了帮朋友配置我重写了README.md，所以没有敢pull自己的代码。如今主分支已经更新了，只需要维护一下版本号这些信息………但反正能用就行，谁管这些玩意呢？无论如何我的folk可以成为历史了，这个issue也可以close了，春季学期再见，没准我那时候就只能抱各位的大腿了！
