### ISSUE TITLE
Minor Fix

### ISSUE THREAD

**Issue by TomQuartz** [zhongxinghong/PKUAutoElective#68]
最新的[commit](https://github.com/zhongxinghong/PKUAutoElective/pull/66#issue-732069982)更新了api之后，loop.py的[这行](https://github.com/zhongxinghong/PKUAutoElective/blob/2882973c9e4e621c35db0bc422acdc52ffa9f131/autoelective/loop.py#L435)需要增加username作为参数
https://github.com/zhongxinghong/PKUAutoElective/blob/2882973c9e4e621c35db0bc422acdc52ffa9f131/autoelective/loop.py#L435
要刷的课在第二页及以后才有可能遇到这个问题

**Comment by guyutongxue** [comment]
Fixed by #69
