### ISSUE TITLE
请问关于IAAA的登录问题

### ISSUE THREAD

**Issue by DeboutSQ** [zhongxinghong/PKUAutoElective#9]
请教一下，曾经刷上过一次课，是在login IAAA后发现course available。因此怀疑可能需要一定时间内登录一次IAAA否则刷新得到的信息是无用的，不知道这个想法对不对，或者可能仅仅是巧合？顺便请问一下新版本是不是不能修改登录间隔了呢？谢谢！

**Comment by zhongxinghong** [comment]
这个是巧合，刷新信息应该都是有效的。

现在改用会话池机制，同时维持几个可用会话，然后开了一个新的线程专门负责重登过期会话，所以现在会话不会再自动过期（也就是你不需要设置登录间隔），而且在遇到过期状态的响应时主动重登，由于采用了会话池机制，遇到偶然的会话失效可以通过立即更换会话来维持主循环，所以不会影响当前的主循环的任务。

**Comment by DeboutSQ** [comment]
原来是这样，多谢多谢
